# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_title',
            new_name='post_title',
        ),
    ]
