# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_hooker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='feature_image',
            field=models.ImageField(upload_to='./blog/media'),
        ),
    ]
