# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170825_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Name',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='anonymous', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.BlogPost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
