# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170825_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='feature_image',
            field=models.ImageField(upload_to='./../static/blog/images/'),
        ),
    ]
