# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170825_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='feature_image',
            field=models.ImageField(upload_to='./'),
        ),
    ]
