# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170911_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='comment_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='commenter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
